name: turnix_flutter
description: >
  A Flutter plugin for fetching WebRTC ICE (STUN/TURN) credentials
  from the Turnix.io API, with support for advanced options
  like regions, TTL, client IP, and per-call parameters.
version: 0.1.2
homepage: https://turnix.io

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # No plugin: purely Dart, platform-agnostic
